---
- hosts: localhost
  connection: local
  gather_facts: true
  become: yes
  tasks:
    - name: yum update
      import_role:
        name: yum_update
    - name: Install AWS Inspector
      import_role:
        name: aws_inspector