name: Archive creation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Push to S3 bucket
        run: |
          mkdir archives
          cd ansible
          zip -r ./archives/ansible.zip *
          cd ../archives/
          aws s3 cp ansible.zip ${{ secrets.BUCKET_NAME }} --acl public-read
